baseURL = "/"
languageCode = "ko-KR"
defaultContentLanguage = "ko"

title = "Workshop"
theme = "learn"

metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false

[params]
  editURL = "https://github.com/nalbam/workshop/edit/master/content/"
  description = "Workshop"
  author = "Jungyoul Yu"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.ko]
title = "Workshop"
weight = 2
languageName = "Korean"

[[Languages.ko.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
identifier = "ds"
url = "https://github.com/nalbam/workshop"
weight = 10

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30
